security:
    encoders:
        FeladatBundle\Entity\User:
            algorithm: sha1
            #iterations: 1
            #encode_as_base64: false
            
    providers:
        our_db_provider:
            entity:
                class: FeladatBundle:User
                property: felhasznalonev
            
    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
        login_firewall:
            pattern:    ^/login$
            anonymous: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
    access_control:
        - { path: ^/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_USER] }