security:
    encoders:
        FeladatBundle\Entity\User:
            algorithm: sha1
            
    providers:
        our_db_provider:
            entity:
                class: FeladatBundle:User
                property: felhasznalonev
            
    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter: login[username]
                password_parameter: login[password]
            logout:
                path:   /logout
                target: /
        login_firewall:
            pattern:    ^/login$
            anonymous: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
    access_control:
        - { path: ^/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_USER] }