FeladatBundle\Entity\Countries:
    type: entity
    table: countries
    uniqueConstraints:
        countryName:
            columns:
                - countryName
        countryName_2:
            columns:
                - countryName
        countryName_3:
            columns:
                - countryName
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        countrycode:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
                default: ''
            column: countryCode
        countryname:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                default: ''
            column: countryName
    lifecycleCallbacks: {  }
