FeladatBundle\Entity\NevElotag:
    type: entity
    table: nev_elotag
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nev:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        leiras:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        letrehozva:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        letrehozo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        modositva:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        modosito:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks:
        prePersist: [ setLetrehozva, setModositva ]
        preUpdate: [ setModositva ]
