FeladatBundle\Entity\Partner:
    type: entity
    table: partner
    indexes:
        szekhely_cim_orszag:
            columns:
                - szekhely_cim_orszag
                - szamlazasi_cim_orszag
                - postazasi_cim_orszag
        tipus:
            columns:
                - tipus
        nev_elotag:
            columns:
                - nev_elotag
        szamlazasi_cim_orszag:
            columns:
                - szamlazasi_cim_orszag
        postazasi_cim_orszag:
            columns:
                - postazasi_cim_orszag
        IDX_312B3E16DC86DDFC:
            columns:
                - szekhely_cim_orszag
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cegnev:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        vezeteknev:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        keresztnev:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        szamlazasiNev:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: szamlazasi_nev
        partnertipus:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        szekhelyCimIrsz:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: szekhely_cim_irsz
        szekhelyCimTelepules:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: szekhely_cim_telepules
        szekhelyCimKozter:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: szekhely_cim_kozter
        szekhelyCimIhazsz:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: szekhely_cim_ihazsz
        szamlazasiCimIrsz:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: szamlazasi_cim_irsz
        szamlazasiCimTelepules:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: szamlazasi_cim_telepules
        szamlazasiCimKozter:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: szamlazasi_cim_kozter
        szamlazasiCimHazsz:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: szamlazasi_cim_hazsz
        postazasiCimIrsz:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: postazasi_cim_irsz
        postazasiCimTelepules:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: postazasi_cim_telepules
        postazasiCimKozter:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: postazasi_cim_kozter
        postazasiCimHazsz:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: postazasi_cim_hazsz
        adoszam:
            type: integer
            nullable: false
            options:
                unsigned: false
        euAdoszam:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: eu_adoszam
        cegbejegyzesiSzam:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: cegbejegyzesi_szam
        telefon:
            type: integer
            nullable: false
            options:
                unsigned: false
        fax:
            type: integer
            nullable: false
            options:
                unsigned: false
        mobil:
            type: integer
            nullable: false
            options:
                unsigned: false
        szuletesnap:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        anyjaNeve:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: anyja_neve
        szigSzam:
            type: string
            nullable: false
            length: 8
            options:
                fixed: true
            column: szig_szam
        letrehozva:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        letrehozo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        modositva:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        modosito:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        tipus:
            targetEntity: Cegtipus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipus:
                    referencedColumnName: id
            orphanRemoval: false
        szekhelyCimOrszag:
            targetEntity: Countries
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                szekhely_cim_orszag:
                    referencedColumnName: id
            orphanRemoval: false
        szamlazasiCimOrszag:
            targetEntity: Countries
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                szamlazasi_cim_orszag:
                    referencedColumnName: id
            orphanRemoval: false
        postazasiCimOrszag:
            targetEntity: Countries
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                postazasi_cim_orszag:
                    referencedColumnName: id
            orphanRemoval: false
        nevElotag:
            targetEntity: NevElotag
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                nev_elotag:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
