FeladatBundle\Entity\Telephely:
    type: entity
    table: telephely
    indexes:
        orszag:
            columns:
                - orszag
        orszag_2:
            columns:
                - orszag
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        partner:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nev:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        irsz:
            type: integer
            nullable: false
            options:
                unsigned: false
        telepules:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        kozter:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        hazsz:
            type: integer
            nullable: false
            options:
                unsigned: false
        telefon:
            type: integer
            nullable: false
            options:
                unsigned: false
        fax:
            type: integer
            nullable: false
            options:
                unsigned: false
        mobil:
            type: integer
            nullable: false
            options:
                unsigned: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        megjegyzes:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        letrehozva:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        letrehozo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        modositva:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        modosito:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        orszag:
            targetEntity: Countries
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                orszag:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
