FeladatBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        felhasznalonev:
            columns:
                - felhasznalonev
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nevElotag:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: nev_elotag
        vezeteknev:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        keresztnev:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        felhasznalonev:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        jelszo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        salt:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
